# Generated by Django 4.0.3 on 2022-09-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hvregistration', '0002_remove_profile_vehivalname_profile_veh_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='veh_no',
            new_name='vehno',
        ),
    ]
