# Generated by Django 4.0.3 on 2022-10-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hvregistration', '0003_rename_veh_no_profile_vehno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uvp',
            field=models.ImageField(blank=True, upload_to='pimages'),
        ),
    ]
