# Generated by Django 4.0.3 on 2022-10-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labourcontractorname', models.CharField(max_length=200)),
                ('labourwork', models.CharField(max_length=500)),
                ('labourinmembers', models.CharField(max_length=200)),
                ('contractoraadharnumber', models.CharField(max_length=20)),
                ('mobilenumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('tehsil', models.CharField(max_length=50)),
                ('uploadlobourgroupimg', models.ImageField(blank=True, upload_to='upimages')),
                ('uploadlobourimg', models.ImageField(blank=True, upload_to='upimages')),
            ],
        ),
    ]
