# Generated by Django 4.0.3 on 2022-10-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractorname', models.CharField(max_length=200, null=True)),
                ('firmname', models.CharField(blank=True, max_length=60)),
                ('experinceinyear', models.CharField(max_length=80)),
                ('licenseno', models.CharField(max_length=50)),
                ('ulp', models.ImageField(blank=True, upload_to='pimages')),
                ('aadharnumber', models.CharField(max_length=20)),
                ('mobilenumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('tehsil', models.CharField(max_length=50)),
                ('uploadworkingimg', models.ImageField(blank=True, upload_to='upimages')),
                ('uploadcontractorphoto', models.ImageField(blank=True, upload_to='upimages')),
            ],
        ),
    ]
